@url = http://localhost:5050
@storyId = 874562136620138496
@userId = f8f09139-0283-4b83-8e92-2d22e40f5e10

###
GET {{url}}

###
GET {{url}}/stories

###
GET {{url}}/stories/{{storyId}}

###
POST {{url}}/stories
Content-Type: application/json

{
  "userId": "{{userId}}",
  "title": "Test 1",
  "text": "Lorem ipsum text",
  "tags": ["dotnet", "csharp"],
  "visibleFrom": null,
  "visibleTo": null,
  "highlighted": false
}

###
POST {{url}}/stories/{{storyId}}/rate
Content-Type: application/json

{
  "userId": "{{userId}}",
  "storyId": "{{storyId}}",
  "rate": 1
}